---
workflow_invocations_dir: "{{ galaxy_root }}/workflows_reporting"
workflow_invocations_venv: "{{ workflow_invocations_dir }}/venv"
workflow_invocations_influxdb_database: workflow_invocations
nginx_access_log: /var/log/nginx/access.log
